task1_2_venv/myapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    #url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('polls.urls')),
]

task1_2_venv/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^find/$', views.find, name='find'),
    url(r'^input/$', views.input, name='input'),
    url(r'^output/$', views.output, name='output'),
]

task1_2_venv/polls/models.py
import datetime, sys, os

from django.db import models
from django.utils import timezone

from sklearn.externals import joblib

sys.path.append(os.path.abspath('polls/naivebayes'))
from .nbModel import naiveBayes


# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Fit():
    dir = os.path.abspath('polls/naivebayes')
    name = 'storedmodel.pkl'

    def __init__(self):
        self.model = joblib.load(os.path.join(dir,name))

    def loadmodel():
        return self.model

task1_2_venv/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic

import requests, sys, os
from bs4 import BeautifulSoup
from sklearn.externals import joblib
from .models import Choice, Question#, Fit

#sys.path.append(os.path.abspath('/naivebayes'))
#from nbModel import naiveBayes
from .models import naiveBayes

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # template = loader.get_template('polls/index.html')
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    # question = get_object_or_404(Question, pk=question_id)
    template_name = 'polls/detail.html'
    # return render(request, 'polls/detail.html', {'question':question})

class ResultsView(generic.DetailView):
    model = Question
    # question = get_object_or_404(Question, pk=question_id)
    # return render(request, 'polls/results.html', {'question': question})
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question': question, 'error_message': "not select a choice",})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def find(request):
    return render(request, 'polls/find.html', {})

def input(request):
    #fit = Fit
    givenurl = request.POST['givenurl']
    if givenurl=='':
        raise Http404("URL is not defined")
    else:
        src = requests.get(givenurl).text
        soup = BeautifulSoup(src, 'html.parser')
        text = soup.select('h1')[0].string

        #fit.pypo()
        dir = os.path.abspath('polls/naivebayes')
        name = 'storedmodel.pkl'
        pred = joblib.load(os.path.join(dir,name))
        call = pred.classify(pred.to_words(text))
        return render(request, 'polls/output.html', {'call':' '+call})

def output(request, text):
    data = text
    return render(request, 'polls/output.html', {})

task1_2_venv/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
  <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
  <input type="submit" value="Vote" />
</form>

task1_2_venv/polls/templates/polls/find.html
<h1>Category Finder</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:input' %}" method="post">
{% csrf_token %}
  Please input a target URL<input type="url" name="givenurl" />
  <input type="submit" value="submit" />
</form>

task1_2_venv/polls/templates/polls/index.html
{% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}
  <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
  {% endfor %}
  </ul>
{% else %}
<p>No polls are available</p>
{% endif %}
<ul>
<li><a href="{% url 'polls:find' %}">Find a category?</a></li>
</ul>

task1_2_venv/polls/templates/polls/input.html
<h1>Category Indicator</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:input' givenurl %}" method="post">
{% csrf_token %}
  <input type="url" name="givenurl" value="Target URL" />
  <input type="submit" value="submit" />
</form>

task1_2_venv/polls/templates/polls/output.html
<body>
<p>Category is{{ call }}</p>
<p><a href="{% url 'polls:find' %}">Find again?</a></p>
</body>

task1_2_venv/polls/templates/polls/results.html
<h1>{{ question.questioin_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
  <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>